### PR TITLE
LRDOCS-5440 alloy editor updates

### PR DESCRIPTION
**Pull request by mwilliams2014**
@jbalsas Here is the updated AlloyEditor buttons tutorial. I think this makes it much more clear what toolbars are available and how to add a button to the toolbar you want. It also includes a sample module for developers to download and build on top of. We can replace this and or link to the blade editorconfigcontributor template once we submit it.

Please review and let me know if you have any doubts. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @mwilliams2014, this looks great!

I think it'd be great to also add a list of available buttons, so people know what they can add. Here's a quick list:

## Add Toolbar
key | description
--- | ---
image |
embed |
camera |
hline |
table | 

## Styles Toolbar
### Image
key | description
--- | ---
imageCenter |
imageLeft |
imageRight |

### Link
key | description
--- | ---
linkEdit |

### Table
key | description
--- | ---
tableHeading |
tableRow |
tableColumn |
tableCell |
tableRemove |

### Text
key | description
--- | ---
bold |
code |
h1 |
h2 |
indentBlock |
italic |
link |
ol |
outdentBlock |
paragraphLeft |
paragraphRight | 
paragraphCenter |
paragrapthJustify |
quote |
removeFormat |
strike |
styles |
subscript |
supersciprt |
twitter |
ul |
underline |

**Comment by mwilliams2014** [comment]
Will do @jbalsas Thanks!

**Comment by mwilliams2014** [comment]
Regarding the config object settings you mentioned, this tutorial is just meant to focus on adding buttons to the AlloyEditor. I'll link to the config settings, but that information will be covered in Modifying an editor configuration most likely.

**Comment by jbalsas** [comment]
Closing, I think this was merged and published! 👏

**Comment by mwilliams2014** [comment]
Yep https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/adding-buttons-to-alloyeditor-toolbars

**Pull request closed without merging**
