### PR TITLE
LRDOCS-5257 Editor Embed Providers

### PR DESCRIPTION
**Pull request by mwilliams2014**
@jbalsas this PR includes the Embed Providers tutorial for the AlloyEditor. I know you're busy, but when you have a chance, can you review the steps. And if you can provide some guidelines or steps for writing your own content provider button code (JSX) that would be helpful. I've looked over the `embed_video.jsx` and `embed_video_edit.jsx` files. Just wondering how to bundle multiple JS files into one? I'm guessing that would be the liferay-npm-bundler. I just need some help with that. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @mwilliams2014, sorry for taking so long!

The new guide looks great! Fantastic job! 👏 

Feel free to send it forward to Rich! 👍

**Comment by mwilliams2014** [comment]
Thanks @jbalsas ! As you know, the AlloyEditor buttons tutorial has been updated and published already here: https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/adding-buttons-to-alloyeditor-toolbars So, I'm going to remove that from this branch, and send the EditorEmbedProvider tutorial to Rich.

**Comment by jbalsas** [comment]
Yeah, that's what I figured. Sounds good to me! :)

**Comment by mwilliams2014** [comment]
Scratch that @jbalsas We have a tutorial on adding buttons to AlloyEditor's Toolbars, but not on Creating the buttons. So, I'll keep that portion of the tutorial and include that with this PR to Rich. Thanks!

**Pull request closed without merging**
