### PR TITLE
LRDOCS-4194 6.2 to 7.1 theme upgrade

### PR DESCRIPTION
**Pull request by mwilliams2014**
@jbalsas here are the 6.2 to 7.1 theme upgrade docs. Please review as soon as possible and let me know if any changes are needed, so we can't get this published. Thanks!

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@jbalsas I have referred to the 7.1 theme tools as "Liferay Themes SDK Tools", rather than saying Theme Generator tools or Node tools, since that isn't entirely accurate. What are your thoughts on using that term instead?

**Comment by jbalsas** [comment]
@marcoscv-work, could you take a look here too?

**Comment by jbalsas** [comment]
Yeah, we might try some of @marcoscv-work themes from back then... or I can get ahold of some others to give this a try!

**Comment by jbalsas** [comment]
Hey @mwilliams2014, this looks great overall. I'm adding some comments below. Could you please review?

### Running the theme upgrade task for 7.2 themes

#### We're currently referring to the Theme SDK in several ways
- Liferay Themes SDK tools
- Liferay Themes SDK ['s Gulp `upgrade` task]
- Liferay Themes SDK build tools
- LIferay Themes SDK
- Liferay Theme SDK development tools
- Liferay Themes SDk tools

I think settling on `Liferay Themes Node.js SDK` should be good to clarify and standardize everything. This should also be applied elsewhere in a separate task.

#### Running `gulp upgrade`

We're currently running `gulp upgrade` twice, which makes sense since our upgrade step only moves from one version to the other. However, in between, we instruct the developer to:

> Open your theme's `package.json` file and update the `liferay-theme-deps` and `liferay-theme-tasks` dependencies to `8.0.0-beta.1`

Couldn't this be done from the begining? The `8.x.x` series should support upgrades from both 6.2-7.0 and 7.0-71.

### Updating 6.2 responsiveness

As far as I can tell, we currently have:
- @mixin xs (media-query(xs))
- @mixin sm (media-query(sm))
- @mixin md (media-query(md))
- @mixin lg (media-query(lg))

And also:
- @mixin media-breakpoint-up
- @mixin media-breakpoint-down

@marcoscv-work, @pat270, is the media query table accurate? Can you provide some additional information for this?

### Updating 6.2 Theme Templates

I think here we might be missing the dynamic include portlet_header extension point. I've filed https://github.com/liferay/liferay-themes-sdk/issues/35 to add support for this in the `upgrade` task.

### Applying Clay Design Patterns

- The first example shows html only, but the second one shows the whole ddm structure.
- Might be worth linking this and probably the intro to the `compatibility-layer` document.

**Comment by mwilliams2014** [comment]
@pat270 @jbalsas These tutorials do upgrade the real life Lunar Resort Theme, created in our 6.2 Developing Themes Learning Path:  https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/6-2/setting-up-the-theme The only issue I ran into was porting the carousel VM file to FTL. Other than that, everything upgraded just fine. Do you feel this theme isn't a good enough use case?

**Comment by mwilliams2014** [comment]
@jbalsas thanks for the review. I'll make the changes you suggested. I think the 8.x.x version doesn't support upgrading 6.2 themes, but I'll see if I missed something.

**Comment by jbalsas** [comment]
Hey @mwilliams2014, @marcoscv-work was trying with his own "Manzanita Theme" today. Some notes:
- Tried to use `liferay-theme-tasks@8.x.x` from the beginning and didn't work for some reason. Could you double check too? If it doesn't work, could you file an issue in the themes-sdk repo? In that case we can keep the tutorial as is, and fix in the future.
- Found a missing automated step and filed https://github.com/liferay/liferay-themes-sdk/issues/36 for it. Might be worth adding a manual note for this?
- Saw some problem with the resources-importer update instructions. He was seeing the following server stacktrace, where as far as I can tell, the important part was that `resources-importer-web` version might be incorrect. Did you run into something like this with the lunar theme?
```
org.osgi.framework.BundleException: Could not resolve module: manzanita-theme-repo-theme [870]_  Unresolved requirement: Import-Package: com.swabunga.spell.engine; resolution:="optional"_  Unresolved requirement: Import-Package: com.swabunga.spell.event; resolution:="optional"_  Unresolved requirement: Import-Package: net.fortuna.ical4j.model; resolution:="optional"_  Unresolved requirement: Import-Package: net.fortuna.ical4j.model.property; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.axis.tools.ant.wsdl; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.hssf.usermodel; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.ss.usermodel; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.portals.bridges.common; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.portals.bridges.struts; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.osgi.web.servlet.jsp.compiler; resolution:="optional"_  Unresolved requirement: Require-Bundle: resources-importer-web; bundle-version="1.0.0"_ [Sanitized]
```

**Comment by mwilliams2014** [comment]
Hey @jbalsas, yeah I'll test it again, but I think I ran into the same issue, that's why I have to run the two separate upgrades that way. I didn't  run into any resources importer issues as far as I know. I'll run through the steps again and see if I do. Thanks!

**Comment by marcoscv-work** [comment]
Hey @mwilliams2014, I was not able to make the resources importer migration correctly following the tutorial steps, I used manzanita theme: https://github.com/marcoscv-work/manzanita-theme

**Comment by mwilliams2014** [comment]
@marcoscv-work did you remove the `required-deployment-context` from your `liferay-plugin-package.properties`?

**Comment by mwilliams2014** [comment]
The latest version 8.0.0.beta-1 works for 6.2-7.0 and 7.0-7.1 theme upgrade. There are some issues I ran into that revert some properties during the upgrade, which I filed here: https://github.com/liferay/liferay-themes-sdk/issues/37

**Comment by marcoscv-work** [comment]
Hey @mwilliams2014 , thanks!
I think the problem was that I have not resources-importer-target-class-name in my theme so I did not replace the classname, I suppose we should not taken for granted the user has this propertie in his teme.

I have added: 
resources-importer-target-class-name=com.liferay.portal.kernel.model.Group 

And it works! thanks!

**Comment by mwilliams2014** [comment]
That's strange @marcoscv-work. You should only need that property if you're importing resources into a site. If you're importing into a site template, that property shouldn't be needed. Sounds like a bug.

**Comment by mwilliams2014** [comment]
@pat270 @marcoscv-work do you have a theme that you would like to use as an example in these upgrade tutorials? Are the mixins that @jbalsas mentioned accurate, or are the ones in the tutorial fine?

**Comment by jbalsas** [comment]
Hey @mwilliams2014, I think the theme you're using is perfectly valid, no need to find a different one 👍

**Comment by jbalsas** [comment]
I think I've seen this sent to rich, so closing here!

**Pull request closed without merging**
