### PR TITLE
LRDOCS-5095 liferay theme tasks

### PR DESCRIPTION
**Pull request by mwilliams2014**
@jbalsas Here is a test of the liferay-theme-tasks tutorials. Instead of including a video, this uses a looping GIF. Our parser already handles this, so I wouldn't have to update my existing script to include the video in the article. What do you think? The tutorial is short and to the point.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @mwilliams2014, this is indeed short and to the point, but I'm not 100% convinced about this one.

I don't think it's a good idea to show required steps in a looped gif (or video). If you miss something, you're forced to wait until the loop repeats. For this in particular, I would expect to have a screenshot of every question/answer step by step or simply a final one if splitting them isn't necessary.

I mentioned using a video for other content like the one I showed you on how you could use the `watch` task to sync different devices and see changes in real life.

Finally, the hierarchy for this `01-theme-generator/01-liferay-theme-tasks/01-gulp-build-task.markdown` seems way off and far from what we discussed about focusing on tutorials that show "how to do something" rather than describe a piece of technology.

Also, to be clear, `theme-tasks` are in now way a subsection of `theme-generator` rather than a whole different project of its own. The generator is used to scaffold different types of projects. The theme-tasks help you develop the theme/layout project.

What do you think? Ping me if you have any doubt about this.

Thanks!

**Comment by mwilliams2014** [comment]
@jbalsas you make some good points. I guess there was a miscommunication. I thought you wanted videos for each task :-) I'll follow the same format as [our layout template one](https://github.com/mwilliams2014/liferay-docs/blob/4edd5d6a83ab132ed276194de641378f5150989b/develop/tutorials/articles/180-themes-and-layout-templates/02-layout-templates/01-layout-templates-with-the-themes-generator.markdown) for the theme tasks, except for the watch task. I'll follow this GIF format for the watch task, if that's ok with you. I'll reorganize and rename these tutorials appropriately as we discussed, I just wanted to get your opinion first before moving forward with the rest of these tutorials. Are there any other tasks that you feel need a GIF? Thanks @jbalsas !

**Comment by jbalsas** [comment]
Hey @mwilliams2014, sounds good. Just to clarify, I don't think any tutorial should use a GIF to explain the main content and describe all the relevant information. 

I would only use videos for additional, slightly tangential information that is visually atractive and motion-based. We can forget about this for now and add it later where we see the opportunity.

**Comment by mwilliams2014** [comment]
I agree @jbalsas. Sounds good.

**Pull request closed without merging**
